<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Project Statisfactory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Statisfactory</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf">Presentation</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page">Report</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Project Statisfactory</h1>
<p class="subtitle lead">Report: Sammy, Griffin, Josh, Elissa, Sancia</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<ol type="1">
<li><strong>Introduction and data</strong></li>
</ol>
<p>With the police killings of Eric Garner, Breonna Taylor, George Floyd, and many others, excess police force on people of color has been brought to the forefront of the American mind. National protests have commanded sustained attention to racialized violence against civilians. A 2020 study based on data from the Washington Post concluded that BIPOC Americans were on average 2-3 times more likely to be killed by police than white Americans (Washington Post, 2022; Lett et al., 2020).</p>
<p>As police brutality and violence has come to a national forefront, data has indicated that the burden of fatal police shootings falls disproportionately on BIPOC in terms of mortality and years of life lost (YLL). Contrary to popular hypotheses, while there was a small decline in deaths of white victims, there was no significant trend in death rates among all other race/ethnic groups (i.e.&nbsp;rates were stable across the 5 year interval). In order, mean deaths were as follows: highest among Native Americans (1.74), then Blacks (1.49), Hispanics (0.74) , Whites (0.57), and Asians (0.25). The authors of the article call for the treatment of police violence as a public health crisis and suggest police demilitarization as a potential intervention. (Lett et al., 2020)</p>
<p>The US Department of Justice Office of Justice Programs conducted studies across 14 large US cities over 2.5 years to identify specific barriers in police accountability for the violence they perpetuate. There is an existing consensus around the high costs of police violence, both in terms of civil lawsuit financial costs to cities and regarding civilian trust in public service entities. Historically, people have perceived that police are internally positioned as “above the law,” which is further complicated by lack of transparency: “The public, to whom police departments should be held accountable, thus cannot ascertain whether, in fact, the police are policing themselves.” Processes to report police officials are largely inefficient and ineffectual, and the individual reporting may fear backlash from the agency. Furthermore, civil lawsuits are rarely carried through to effect appropriate punishment, and the oversight procedures that do take place often do not provide adequate supervision, allowing offending officers back into the field with little regulation (Collins, 1998).</p>
<p>Contributing to further distrust is the concept of adultification: a phenomenon in which “notions of innocence and vulnerability are not afforded to certain children… the impact results in children’s rights being either diminished or not upheld” (Davis &amp; Marsh, 2020). Current literature has focused primarily on this phenomenon in black children, as it provides a theoretical framework for the tendency to view black children as older than they are. As a direct result, more physical and systemic violence may be mounted against them (Koch &amp; Kozhumam, 2022).</p>
<p>According to a study by the Proceedings of the National Academy of Sciences, men are far more likely to be subject to police violence; the average lifetime odds of being killed by police is about 1 in 2,000 for men and about 1 in 33,000 for women (Edwards et al., 2019). Risk of death by police for all gender and race groups peak between the ages of 20 y and 35 y and decline with age. This pattern is similar for non-fatal police violence. Studies conclude that police violence is a leading cause of death for young men of color, but not for any other demographic.</p>
<p>Data was sourced from the Washington Post repository on fatal police shootings between 2015-2020, which is dependent on curated news reports and thus may exclude necessary data such as gender and minority status. It was published with the intent to bolster the evidence-base of police killings for the Black Lives Matter movement. During this time interval, 5367 fatalities were recorded, of which 4740 offered significant racial data for analysis, and 4653 included both sufficient racial and age data for YLL calculation. The data was originally collected by manually combing through local news reports, combining information from law enforcement websites, social media, and other databases (including Fatal Encounters and the “Killed by Police” project). Data collection started in 2015 spurred by a slew of fatal shootings, and the information was updated in 2022. There are no apparent ethical concerns with data collection or presentation.</p>
<p>The observations include details about police-involved killings in the United States. The variables include race, age, gender, armed vs not armed status, location, and if the person killed had a mental illness. The observations are primarily focused on key descriptions of the person killed, but do include some details about the police involved (including the presence/lack of a police body camera and the threat of the person as perceived by police).</p>
<p>The present study aims to investigate the following research question: How does the average age differ by race and gender for victims of police shootings, and who experiences more violence (shot and tasered) compared to just shot?</p>
<p>This question is important because it directly draws a distinction between the type of violence people experience based on their race. Findings may indicate that younger people of certain races are targeted with disproportionate police violence, which could lead to a push for police reform. Investigating the intricacies of police violence through the lens of race and age is crucial to identifying systemic issues in the criminal justice system.</p>
<p>The research topic seeks to investigate if young people of minority races or men are targeted with more police violence. We will analyze the variables “Person.Age,” “Person.Race,” and “Shooting.Manner” to narrow down which demographic experiences “shot and Tasered” vs “shot.” The age variable is quantitative, and the race and shooting manner variables are categorical. We hypothesize that minority victims (African American, Hispanic, Native American, other) are more likely to be shot and tasered (experience more violence) at a younger age than white victims. We also hypothesize that male victims at a lower age are more likely to be shot and tasered than female victims and experience more violence overall.</p>
<ol start="2" type="1">
<li><strong>Methodology</strong></li>
</ol>
<p>AIC was used as a model selection criterion as it punishes the addition of variables that do not confer advantages in modeling the data by increasing AIC. Therefore, the model with the lower AIC is usually a better model of the data (but other factors must be taken into account as well). Specifically, we used forward selection. First, we started with a model that had no predictors, then we fit each variable in a logistic regression model with a single independent variable to investigate which one has the lowest AIC. We compared the AIC scores after adding variables to the model with no predictors to select the best model with 1 additional explanatory variable. Then, we added variables in different combinations to reach the best model with more complex interactions and inform our later graphics. We considered the main variables of our study (age, race, and gender) to find which were the most prevalent in predicting level of police violence.</p>
<p>We plan to represent our four variables through a series of six graphics. Our preliminary graph will be a box plot to compare the ages of those shot vs shot and tasered. We will facet by shot/shot tasered, and our axis values will be age. This will help create a baseline understanding of what ages are most vulnerable to more violence. Having this knowledge will add significance to the future graphs that incorperate gender and race.</p>
<p>Our next two graphs will compare age, race, and shot/shot tasered. We will create one histogram faceted by race and filled by age, filtered for those only shot. Our next graph will be the same, except filtered for those shot and tasered; this will help visualize how age differs by race between those just shot and those shot and tasered.</p>
<p>Next, we will create two overlaid density plots to compare age, gender, and shot/shot tasered. The first will be for females and put age on the x-axis and density on the y-axis, overlaying the graphs for <code>shot</code> and <code>shot and Tasered</code>. The second will be the same method, except using a graph filtered for males. These two graphs have a similar purpose to graphs 2 and 3, except they will be examining the affect of gender on level of violence instead of race.</p>
<p>Finally, we will include a graph of our additional variable, if the victim was fleeing or not (and how so). We predict that this variable might have an impact on if the victim was shot or shot and tasered, so we think it is important to include a representation of it. We will use a histogram with the three possibilities for fleeing on the x-axis (not fleeing, car, foot), and we will fill the graph by shot or shot and tasered. When making equations to analyze our data, we can use multiple linear regression analysis to estimate the importance and relevance of the extra explanatory variable (fleeing) and the response variable (level of violence). This helps account for fleeing status as a potentially confounding variable.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   1.0.0 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.5.0 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
── Attaching packages ────────────────────────────────────── tidymodels 1.0.0 ──

✔ broom        1.0.2     ✔ rsample      1.1.1
✔ dials        1.1.0     ✔ tune         1.0.1
✔ infer        1.0.4     ✔ workflows    1.1.2
✔ modeldata    1.0.1     ✔ workflowsets 1.0.0
✔ parsnip      1.0.3     ✔ yardstick    1.1.0
✔ recipes      1.0.3     

── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Search for functions across packages at https://www.tidymodels.org/find/

Rows: 6569 Columns: 16
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (9): Person.Name, Person.Gender, Person.Race, Incident.Location.City, I...
dbl  (4): Person.Age, Incident.Date.Month, Incident.Date.Day, Incident.Date....
lgl  (2): Factors.Mental-Illness, Shooting.Body-Camera
date (1): Incident.Date.Full

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 6,569
Columns: 16
$ Person.Name              &lt;chr&gt; "Tim Elliot", "Lewis Lee Lembke", "John Paul …
$ Person.Age               &lt;dbl&gt; 53, 47, 23, 32, 39, 18, 22, 35, 34, 47, 25, 3…
$ Person.Gender            &lt;chr&gt; "Male", "Male", "Male", "Male", "Male", "Male…
$ Person.Race              &lt;chr&gt; "Asian", "White", "Hispanic", "White", "Hispa…
$ Incident.Date.Month      &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ Incident.Date.Day        &lt;dbl&gt; 2, 2, 3, 4, 4, 4, 5, 6, 6, 6, 6, 7, 7, 7, 7, …
$ Incident.Date.Year       &lt;dbl&gt; 2015, 2015, 2015, 2015, 2015, 2015, 2015, 201…
$ Incident.Date.Full       &lt;date&gt; 2015-01-02, 2015-01-02, 2015-01-03, 2015-01-…
$ Incident.Location.City   &lt;chr&gt; "Shelton", "Aloha", "Wichita", "San Francisco…
$ Incident.Location.State  &lt;chr&gt; "WA", "OR", "KS", "CA", "CO", "OK", "AZ", "KS…
$ Factors.Armed            &lt;chr&gt; "gun", "gun", "unarmed", "toy weapon", "nail …
$ `Factors.Mental-Illness` &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRU…
$ `Factors.Threat-Level`   &lt;chr&gt; "attack", "attack", "other", "attack", "attac…
$ Factors.Fleeing          &lt;chr&gt; "Not fleeing", "Not fleeing", "Not fleeing", …
$ Shooting.Manner          &lt;chr&gt; "shot", "shot", "shot and Tasered", "shot", "…
$ `Shooting.Body-Camera`   &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRU…</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 6,262
Columns: 16
$ Person.Name              &lt;chr&gt; "Tim Elliot", "Lewis Lee Lembke", "John Paul …
$ Person.Age               &lt;dbl&gt; 53, 47, 23, 32, 39, 18, 22, 35, 34, 47, 25, 3…
$ Person.Gender            &lt;chr&gt; "Male", "Male", "Male", "Male", "Male", "Male…
$ Person.Race              &lt;chr&gt; "Asian", "White", "Hispanic", "White", "Hispa…
$ Incident.Date.Month      &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ Incident.Date.Day        &lt;dbl&gt; 2, 2, 3, 4, 4, 4, 5, 6, 6, 6, 6, 7, 7, 7, 7, …
$ Incident.Date.Year       &lt;dbl&gt; 2015, 2015, 2015, 2015, 2015, 2015, 2015, 201…
$ Incident.Date.Full       &lt;date&gt; 2015-01-02, 2015-01-02, 2015-01-03, 2015-01-…
$ Incident.Location.City   &lt;chr&gt; "Shelton", "Aloha", "Wichita", "San Francisco…
$ Incident.Location.State  &lt;chr&gt; "WA", "OR", "KS", "CA", "CO", "OK", "AZ", "KS…
$ Factors.Armed            &lt;chr&gt; "gun", "gun", "unarmed", "toy weapon", "nail …
$ `Factors.Mental-Illness` &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRU…
$ `Factors.Threat-Level`   &lt;chr&gt; "attack", "attack", "other", "attack", "attac…
$ Factors.Fleeing          &lt;chr&gt; "Not fleeing", "Not fleeing", "Not fleeing", …
$ Shooting.Manner          &lt;chr&gt; "shot", "shot", "shot and Tasered", "shot", "…
$ `Shooting.Body-Camera`   &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRU…</code></pre>
</div>
</div>
<p>Forward selection with AIC:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2551.999</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2553.86</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2558.469</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2554.007</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2560.465</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2563.574</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2555.871</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2559.779</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2562.553</code></pre>
</div>
</div>
<p>Based on the results, the model with the lowest AIC of one additional variable is age. Once examining the effects of gender, race and age on shooting manner independently of one another, we conclude the most prominent factors related to the violence level are age, followed by gender, followed by race. Between the additive models, age and gender had a lower AIC than age and race, and the addition of all three variables had the highest AIC but the result is worth exploring further through graphics. In the interactive models, age and gender also had a lower AIC than age and race. This means we may want to further investigate the correlation between age and gender in predicting shooting manner. For our purposes, we also decided to examine how race effects level of violence because many current systemic issues in policing involve race. However, this AIC testing gave a baseline understanding that in this data set, age is the most prominent predictor of shooting manner followed by gender.</p>
<ol type="1">
<li>Age, shot vs age, shot and tasered</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/boxplot-shot/age-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Hypothesis test</p>
<p><span class="math inline">\(H_o\)</span>: <span class="math inline">\(\mu_1 = \mu_2\)</span> The mean age for people shot vs shot and tasered is equal. <span class="math inline">\(H_a\)</span> : <span class="math inline">\(\mu_1 \neq \mu_2\)</span> The mean age for people shot and tasered is different than the mean age for shot alone.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Shooting.Manner  mean_age
  &lt;chr&gt;               &lt;dbl&gt;
1 shot                 37.1
2 shot and Tasered     36.9</code></pre>
</div>
</div>
<p>obs_stat: <span class="math inline">\(\bar{x_1} - \bar{x_2}\)</span> = 37.13372 - 36.85802 = 0.2757</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1   0.357</code></pre>
</div>
</div>
<p>The probability of observing a difference in means of 0.2757 years or more extreme between people shot and tasered vs shot alone, given the null assumption that the true difference in means is 0 years between groups, is 0.357 Therefore, we fail to reject the null hypothesis under the significance level alpha = 0.05 and conclude that there is weak evidence to support the alternative hypothesis.</p>
<ol start="2" type="1">
<li>Age, race, shot</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/age-race-shot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  Person.Race      mean_age
  &lt;chr&gt;               &lt;dbl&gt;
1 African American     32.6
2 Asian                36.8
3 Hispanic             33.6
4 Native American      31.9
5 Other                32.4
6 Unknown              42.4
7 White                40.1</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Age, race, shot and tasered</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/age-race-shot-and-tasered-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  Person.Race      mean_age
  &lt;chr&gt;               &lt;dbl&gt;
1 African American     34.5
2 Asian                33.8
3 Hispanic             35.7
4 Native American      37.6
5 Other                34  
6 Unknown              41.1
7 White                38.3</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Age and shot/shot tasered (female)</li>
</ol>
<p>Hypothesis test <span class="math inline">\(H_o\)</span>: <span class="math inline">\(\mu_1 = \mu_2\)</span> The mean age for females shot vs shot and tasered is equal. <span class="math inline">\(H_a\)</span> : <span class="math inline">\(\mu_1 \neq \mu_2\)</span> The mean age for females shot and tasered is different than the mean age for shot alone.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Shooting.Manner  mean_age
  &lt;chr&gt;               &lt;dbl&gt;
1 shot                 37.4
2 shot and Tasered     38.4</code></pre>
</div>
</div>
<p>obs_stat: <span class="math inline">\(\bar{x_1} - \bar{x_2}\)</span> = 38.40 - 36.35714 = 2.04286</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1   0.303</code></pre>
</div>
</div>
<p>The probability of observing a difference in means of 2.04 years or more extreme between females shot and tasered vs shot alone, given the null assumption that the true difference in means is 0 years between groups, is 0.303. Therefore, we fail to reject the null hypothesis under the significance level alpha = 0.05 and conclude that there is weak evidence to support the alternative hypothesis.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/graph4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="5" type="1">
<li>Age and shot/shot tasered (male)</li>
</ol>
<p>Hypothesis test <span class="math inline">\(H_o\)</span>: <span class="math inline">\(\mu_1 = \mu_2\)</span> The mean age for males shot vs shot and tasered is equal. <span class="math inline">\(H_a\)</span> : <span class="math inline">\(\mu_1 \neq \mu_2\)</span> The mean age for males shot and tasered is different than the mean age for shot alone.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Shooting.Manner  mean_age
  &lt;chr&gt;               &lt;dbl&gt;
1 shot                 37.1
2 shot and Tasered     36.8</code></pre>
</div>
</div>
<p>obs_stat: <span class="math inline">\(\bar{x_1} - \bar{x_2}\)</span> = 37.12306 - 36.80892 = 0.31414</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1   0.459</code></pre>
</div>
</div>
<p>The probability of observing a difference in means of 0.69725 years or more extreme between males shot and tasered vs shot alone, given the null assumption that the true difference in means is 0 years between groups, is 0.459 Therefore, we fail to reject the null hypothesis under the significance level alpha = 0.05 and conclude that there is weak evidence to support the alternative hypothesis.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/graph5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="6" type="1">
<li>Fleeing Manner and shot vs shot and tased</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  term                       estimate std.error statistic  p.value
  &lt;chr&gt;                         &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)                  -3.67      0.203    -18.1  2.25e-73
2 Factors.FleeingFoot           0.817     0.255      3.20 1.37e- 3
3 Factors.FleeingNot fleeing    0.880     0.214      4.11 3.94e- 5
4 Factors.FleeingOther          1.07      0.329      3.26 1.12e- 3
5 Factors.Fleeingunknown        0.635     0.306      2.08 3.78e- 2</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/multiple-vars-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Predictions and inferences:</strong></p>
<ol type="1">
<li><p>We predict that younger age ranges will experience higher rates of violence (shot and tasered vs shot). People in the age range of young adult to mid-thirties (approximately 20 - 35) will experience higher rates of shot and tasered vs just shot. (graph 1)</p></li>
<li><p>(prediction for comparing 2 and 3) We predict that Hispanic and African-American targets will be shot and tased comparatively more than just shot; oppositely, white and Asian targets will be shot comparatively more than shot and tased.</p></li>
<li><p>(prediction for comparing 4 and 5) We predict that male gender targets will be shot and tased comparatively more than just shot; oppositely, female gender targets will be shot comparatively more than shot and tased.</p></li>
<li><p>When making a visualization of fleeing status vs.&nbsp;shot/shot and tased, we infer that the victim’s fleeing status affects the level of violence. We predict that those not fleeing will be shot and tased at the highest rate compared to just shot (because they’re in close proximity to tase), followed by fleeing on foot, and finally fleeing with a car. This prediction is based on how convenient and easy it is to tase and shoot compared to just shooting.</p></li>
</ol>
<p><strong>3. Results</strong></p>
<ol type="1">
<li><p>Graph 1: This graph relates age to the shooting manner in which the individual was targeted (shot and tased vs shot alone). For both groups, the average age at which they were targeted was between ages 25-40, and it initially appears from the data visualization that age did not differ significantly between the groups of people shot and tasered vs shot alone. This was confirmed with hypothesis testing. Summary statistics were calculated for both shot and tasered (<span class="math inline">\(\mu\)</span> = 36.08) and shot alone (<span class="math inline">\(\mu\)</span> = 35.35) groups, and a p-value of 0.214 was calculated given the null hypothesis that the difference in means between groups was 0 years. As a result, we fail to reject the null hypothesis and conclude weak evidence for the alternative hypothesis that age significantly differs between groups.</p></li>
<li><p>Graphs 2 and 3: These two graphs shows the effect of race and age on victims shot by the police. The trend across graphs was that the most likely age range to be shot for all demographics is in the late twenties to thirties, especially in the white population. Specifically, the most likely age to be shot…This matched with our predictions. The races with the highest count of those shot were in the African American, White, and Hispanic populations. We assumed that those of minority populations would be among the most targeted, and the data partially represents that hypothesis. This graph shows the effect of race and age on victims who were both shot and tasered. Again the trends center on those in the African American, Hispanic, and White populations, however the age spread is wider and older than the graphs of those who were only shot. Contrary to our assumptions, this seems to indicate that those shot and tasered span victims ages twenty to fifty in all races, and there is no definitive correlation between age and whether or not someone was shot, or shot and tasered. However, there were peaks in the graph in victims of African American descent in their late twenties and early thirties, as well as white and Hispanic victims in their thirties. The majority of those shot and tasered were in their twenties to thirties and African American, Hispanic, and white races. However, this is very similar to the trend among those who were shot and not tasered, and there is no definitive effect of race and age on the police officer’s shooting manner.</p></li>
<li><p>Graph 4: This graph is showing the overlaid density plot for females, comparing both <code>shot</code> and <code>shot and Tasered</code>. As we can see from the density plot, there seems to be three hotspots at which females experience more violence (<code>shot and Tasered</code>), around ages 10, 37, and 60. However, based on the hypothesis testing, there does not appear to be sufficient evidence that the mean age is really any different across the two categories. So, overall, the mean age at which people encounter the different types of violence does not appear to have any significant difference, but at certain ages, there does appear to be a greater or lesser probability to experience one type of violence over another.</p></li>
<li><p>Graph 5: Compared to the graph for females, the male graph is pretty much indistinguishable when comparing <code>shot</code> and <code>shot and Tasered</code>. This seems to suggest that at least for males, whether or not they were tasered in addition to being shot did not really matter. Thus, the hypothesis that males will experience more violence (<code>shot and Tasered</code>) at younger ages seems to be disproven. This matches with our hypothesis testing which gave insufficient evidence to reject the null hypothesis (that mean age does not differ across categories).</p></li>
<li><p>Graph 6: This graph shows the relationship between fleeing manner and whether or not someone was shot, or shot and tasered. Overall, there is little correlation between these two variables. There is a slightly higher probability that someone was shot and tasered if they were not fleeing or on foot as opposed to in a car or pursuing an unknown/other manner of departure. However, there is not a large enough correlation to relate shooting manner and fleeing manner.</p></li>
</ol>
<p><strong>Discussion</strong></p>
<p>Our overarching goal was to find how race and gender impact the average age of victims of police violence, and if those factors affect the level of violence they experience - shot vs shot and tasered. Overall, we concluded that age itself is relatively consistent between levels of violence, but minority groups experience both types of violence at younger ages (32 for African Americans, 36 for Asians, 33 for Hispanics, 31 for Native Americans) than white people (40). Gender also plays a role in the age, and type of violence that perpetrators experience. The mean probability of getting shot vs shot and tasered for males differs less by age than it does for females, but males in general experience more police violence (shot and tasered compared to just shot). Our findings confirm our hypothesis that minorities and men experience police violence at a higher rate, but we were wrong in predicting that younger people of minority races and both genders would be shot and tasered more than just shot - hypothesis tests showed that age for each race and gender did not determine level of violence.</p>
<p>Potential limitations of our analysis is prioritizing interactions between age and race/gender instead of also looking at the interactions between gender and race separately. Additionally, there is significantly more data on men than women so to truly get an understanding of how gender predicts level of violence it would be helpful to use a dataset with more comprehensive data. Finally, we analyzed level of violence by comparing shot to shot and tased, but it would make sense to also compare these findings to police stoppages with no violence and interactions that end in harm or death. In the future it would be interested to include more detailed ways of tracking police violence (such as including different weapons used or time-of-encounter). Additionally, future work may look at what strategies can be taken to limit violence based on what actions have been successful in the past.</p>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>